name: Generate Trophy Image

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  generate-trophy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: Achintha2002
          file: trophy.svg
          theme: tokyonight
          max-cols: 6
          max-rows: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push trophy.svg
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add trophy.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update trophy.svg"
          git push
